"use strict";
// Authorized worker only. No server, dependencies or network.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const model=require('./model.js'),{S2,R2}=model.fixtures();
const near=(a,b)=>assert.ok(Math.abs(a-b)<=Math.max(1e-9,Math.abs(b)*1e-9),`${a} != ${b}`);
const copy=x=>JSON.parse(JSON.stringify(x)),sum=(a,f)=>a.reduce((s,x)=>s+f(x),0);
const q=6371*Math.PI/180*.01,k=q*.12,logs=[],runs=[];
function test(name,f){f();logs.push({name,status:'PASS'});}
// Separate spherical cosine distance and raw order ledger, not model/UI aggregators.
function km(a,b){const r=Math.PI/180;return 6371*Math.acos(Math.max(-1,Math.min(1,Math.sin(a.lat*r)*Math.sin(b.lat*r)+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.cos((a.lon-b.lon)*r))));}
function audit(r){
 for(const name of ['baseline','optimized']){
  const a=r[name],p=r.parameters,plan=a.planning,o=a.simulation.orders,v=a.simulation.kpis;
  assert.ok(a.selectedHubs.length<=p.maxHubs);assert.equal(new Set(o.map(x=>x.id)).size,o.length);
  for(const c of r.data.customers){const n=Math.round(c.demandPerDay*p.demandMultiplier);assert.equal(sum(plan.allocations.filter(x=>x.customerId===c.id),x=>x.unitsPerDay)+sum(plan.unserved.filter(x=>x.customerId===c.id),x=>x.unitsPerDay),n);assert.equal(o.filter(x=>x.customerId===c.id).length,n*p.days);}
  for(const h of r.data.facilities){const used=sum(plan.allocations.filter(x=>x.hubId===h.id),x=>x.unitsPerDay);assert.ok(used<=Math.round(h.capacityPerDay*p.capacityMultiplier));if(!a.selectedHubs.includes(h.id))assert.equal(used,0);for(let d=0;d<p.days;d++){const n=o.filter(x=>x.hubId===h.id&&x.day===d&&x.dispatchedAt!==null).length;assert.ok(n<=Math.round(h.capacityPerDay*p.capacityMultiplier));if(h.id===p.disruptionHub&&d<p.disruptionDays)assert.equal(n,0);}}
  for(const x of plan.allocations){assert.ok(Number.isInteger(x.unitsPerDay)&&x.unitsPerDay>0);const h=r.data.facilities.find(h=>h.id===x.hubId),c=r.data.customers.find(c=>c.id===x.customerId);assert.ok(Math.abs(x.distanceKm-km(h,c))<1e-5);near(x.unitCost,x.distanceKm*.12);}
  const fixed=sum(r.data.facilities.filter(h=>a.selectedHubs.includes(h.id)),h=>h.fixedCostPerDay);
  near(plan.fixedCostPerDay,fixed);near(plan.transportCostPerDay,sum(plan.allocations,x=>x.unitsPerDay*x.distanceKm*.12));near(plan.unservedPenaltyPerDay,sum(plan.unserved,x=>x.unitsPerDay)*200);near(plan.totalCostPerDay,fixed+plan.transportCostPerDay+plan.unservedPenaltyPerDay);
  const delivered=o.filter(x=>x.deliveredAt!==null),onTime=delivered.filter(x=>x.deliveredAt<=x.dueAt).length;
  for(const x of o){assert.equal(x.quantity,1);assert.ok(x.exogenousDelayHours>=0&&x.exogenousDelayHours<3);near(x.dueAt,x.createdAt+8);if(x.deliveredAt!==null){near(x.dispatchedAt,x.createdAt+1);near(x.deliveredAt,x.dispatchedAt+x.distanceKm/50+x.exogenousDelayHours);}else assert.equal(x.dispatchedAt,null);}
  assert.equal(v.demand,o.length);assert.equal(v.delivered,delivered.length);assert.equal(v.unserved,o.length-delivered.length);assert.equal(v.onTime,onTime);
  near(v.serviceRate,o.length?delivered.length/o.length:0);near(v.onTimeRate,o.length?onTime/o.length:0);near(v.meanLeadHours,delivered.length?sum(delivered,x=>x.deliveredAt-x.createdAt)/delivered.length:0);
  near(v.fixedCost,fixed*p.days);near(v.transportCost,sum(delivered,x=>x.distanceKm*.12));near(v.penaltyCost,(o.length-delivered.length)*200);near(v.totalCost,v.fixedCost+v.transportCost+v.penaltyCost);
  for(const d of a.simulation.daily){const items=o.filter(x=>x.day===d.day);assert.deepEqual(d,{day:d.day,demand:items.length,delivered:items.filter(x=>x.deliveredAt!==null).length,onTime:items.filter(x=>x.deliveredAt!==null&&x.deliveredAt<=x.dueAt).length,unserved:items.filter(x=>x.deliveredAt===null).length});}
 }
 assert.ok(r.optimized.planning.totalCostPerDay<=r.baseline.planning.totalCostPerDay+1e-7);
 assert.deepEqual(r.baseline.simulation.orders.map(x=>[x.id,x.exogenousDelayHours]),r.optimized.simulation.orders.map(x=>[x.id,x.exogenousDelayHours]));
}
function run(label,params={}){params={data:S2,...params};const r=model.run(params);audit(r);runs.push({label,params,baseline:{selectedHubs:r.baseline.selectedHubs,planning:r.baseline.planning,kpis:r.baseline.simulation.kpis},optimized:{selectedHubs:r.optimized.selectedHubs,planning:r.optimized.planning,kpis:r.optimized.simulation.kpis}});return r;}
test('합성 provenance 및 최초 지역 UI와 생략 API 일치',()=>{for(const data of Object.values(model.fixtures()))assert.equal(data.provenance.kind,'synthetic');assert.deepEqual(model.run().data,model.run({data:model.fixtures().regional}).data);assert.deepEqual(model.defaults(),model.fixtures().regional);assert.deepEqual(model.run(),model.run());assert.match(fs.readFileSync('index.html','utf8'),/id="case-select"><option value="regional"/);});
let normal,blocked,reverse;
test('S2 전체 7집합과 작은 해',()=>{normal=run('S2 정상');assert.equal(normal.candidates.length,7);const expected=[1600,2+24*k,2+16*k,4+12*k,2+24*k,4+8*k,4+12*k];normal.candidates.forEach((x,i)=>near(x.totalCostPerDay,expected[i]));assert.deepEqual(normal.optimized.selectedHubs,['F2']);near(normal.baseline.simulation.kpis.totalCost,28+56*k);near(normal.optimized.simulation.kpis.totalCost,14+112*k);assert.equal(normal.optimized.simulation.kpis.onTimeRate,1);near(normal.optimized.simulation.kpis.meanLeadHours-normal.baseline.simulation.kpis.meanLeadHours,q/50);});
test('R2 역방향 재배치 최종 해',()=>{reverse=run('R2',{data:R2,days:1});assert.deepEqual(reverse.optimized.planning.allocations.map(x=>[x.hubId,x.customerId,x.unitsPerDay]),[['A','D2',1],['B','D1',1]]);near(reverse.optimized.planning.totalCostPerDay,4*k);});
test('수요 0과 용량 0 공집합',()=>{const z=run('수요0',{demandMultiplier:0,days:1});assert.deepEqual(z.optimized.selectedHubs,[]);assert.equal(z.baseline.simulation.kpis.totalCost,4);const c=run('용량0',{capacityMultiplier:0,days:1});assert.equal(c.optimized.simulation.kpis.totalCost,1600);assert.equal(c.baseline.simulation.kpis.totalCost,1604);});
test('용량 부족과 중복 벌점',()=>{const r=run('R2 부족',{data:R2,days:1,demandMultiplier:2});near(r.optimized.simulation.kpis.totalCost,400+3*k);const d=run('R2 부족 장애',{data:R2,days:1,demandMultiplier:2,disruptionHub:'A',disruptionDays:1});near(d.optimized.simulation.kpis.totalCost,600+2*k);assert.equal(d.optimized.simulation.kpis.unserved,3);});
test('전기간 및 2일 장애',()=>{blocked=run('F2 전기간 장애',{disruptionHub:'F2',disruptionDays:7});assert.equal(blocked.optimized.simulation.kpis.totalCost,11214);assert.equal(blocked.optimized.simulation.kpis.delivered,0);const r=run('F2 2일 장애',{disruptionHub:'F2',disruptionDays:2});near(r.optimized.simulation.kpis.totalCost,14+80*k+3200);assert.equal(r.optimized.simulation.kpis.delivered,40);});
test('반올림 .49/.5/1.5',()=>{for(const v of [.49,.5,1.5]){const r=run('반올림 '+v,{data:R2,days:1,demandMultiplier:v,capacityMultiplier:v});assert.equal(r.optimized.planning.totalDemandPerDay,2*Math.round(v));near(r.optimized.planning.totalCostPerDay,4*k*Math.round(v));}});
test('거점 수 및 용량 단조성',()=>{for(const key of ['maxHubs','capacityMultiplier']){let prev=Infinity;for(const v of key==='maxHubs'?[1,2,3]:[.8,1,1.2]){const r=run(key+v,{[key]:v});assert.ok(r.optimized.planning.totalCostPerDay<=prev+1e-9);prev=r.optimized.planning.totalCostPerDay;if(key==='maxHubs'&&v===1)assert.deepEqual(r.baseline.selectedHubs,['F1']);}}});
test('수요·고정비·seed 민감도',()=>{for(const v of [.8,1,1.2,3])run('수요'+v,{demandMultiplier:v});for(const v of [0,2,20]){const data=copy(S2);data.facilities.forEach(h=>h.fixedCostPerDay=v);const r=run('고정비'+v,{data});if(v===0)assert.deepEqual(r.optimized.selectedHubs,['F1','F3']);}for(const seed of [1,42,2026])run('seed'+seed,{seed});});
test('재현성·장애 간 공통 지연·JSON',()=>{assert.deepEqual(model.run({data:S2}),normal);assert.deepEqual(JSON.parse(JSON.stringify(normal)),normal);assert.deepEqual(normal.optimized.simulation.orders.map(o=>o.exogenousDelayHours),blocked.optimized.simulation.orders.map(o=>o.exogenousDelayHours));});
test('정확 납기 경계 <=',()=>{for(const e of [-1e-6,0,1e-6])assert.equal(model.isOnTime({deliveredAt:9+300/50+1+e,dueAt:16}),e<=0);assert.equal(model.isOnTime({deliveredAt:null,dueAt:16}),false);});
test('별도 장거리 합성 입력의 실제 납기 지연',()=>{const data=copy(R2);data.facilities.forEach(h=>{h.lat=37;h.capacityPerDay=8;});data.customers.forEach(c=>{c.lat=39.7;c.demandPerDay=4;});data.provenance.version='L2-long-distance-synthetic';const r=run('L2 장거리',{data});assert.equal(r.optimized.simulation.kpis.serviceRate,1);assert.ok(r.optimized.simulation.kpis.onTimeRate>0&&r.optimized.simulation.kpis.onTimeRate<1);assert.equal(r.optimized.simulation.kpis.penaltyCost,0);});
test('범위·기간·최대 후보 32개',()=>{run('30일',{days:30});run('배율상한',{demandMultiplier:3,capacityMultiplier:3});const data=copy(S2);data.facilities.push({...data.facilities[0],id:'F4'},{...data.facilities[0],id:'F5'});assert.equal(run('5시설',{data,maxHubs:5}).candidates.length,32);for(const p of [{days:0},{days:31},{demandMultiplier:-1},{capacityMultiplier:3.1},{maxHubs:0},{disruptionHub:'missing'},{days:1,disruptionDays:2},{seed:NaN}])assert.throws(()=>model.run(p));});
// Minimal DOM harness: exercises app handlers and attributes, NOT a real browser.
class Element{
 constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attrs={};this.events={};this.value='';this.hidden=false;}
 setAttribute(k,v){this.attrs[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}
 append(...n){this.children.push(...n);} replaceChildren(...n){this.children=n;} addEventListener(k,f){this.events[k]=f;}
 querySelectorAll(sel){const key=sel.slice(1,-1).slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return this.children.flatMap(n=>[...(key in n.dataset?[n]:[]),...n.querySelectorAll(sel)]);}
}
test('화면 핸들러·독립 KPI·투영·선택·재계산 (DOM 모형)',()=>{
 const ids={};for(const id of ['model-form','model-results','model-checks','network-map','scenario-select','top-kpis','comparison-summary','selection-detail','assumptions','data-provenance','scenario-table','capacity-table','case-select','fixed-cost-multiplier','seed','days','demand-multiplier','capacity-multiplier','max-hubs','disruption-hub','disruption-days'])ids[id]=new Element('div');
 const values={'case-select':'regional','fixed-cost-multiplier':1,seed:42,days:7,'demand-multiplier':1,'capacity-multiplier':1,'max-hubs':2,'disruption-hub':'','disruption-days':0,'scenario-select':'optimized'};Object.entries(values).forEach(([k,v])=>ids[k].value=String(v));
 const document={getElementById:id=>ids[id],createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),createTextNode:t=>{const n=new Element('text');n.textContent=t;return n;}};
 vm.runInNewContext(fs.readFileSync('app.js','utf8'),{document,window:{DASNetwork:model}});
 function check(s,r){const a=r[s],v=a.simulation.kpis;for(const id of ['top-kpis','model-results']){assert.equal(ids[id].dataset.scenario,s);near(+ids[id].dataset.totalCost,v.totalCost);near(+ids[id].dataset.serviceRate,v.serviceRate);near(+ids[id].dataset.onTimeRate,v.onTimeRate);assert.equal(+ids[id].dataset.demand,v.demand);assert.equal(+ids[id].dataset.delivered,v.delivered);}for(const n of ids['top-kpis'].querySelectorAll('[data-metric]'))near(+n.dataset.value,v[n.dataset.metric]);assert.equal(ids['network-map'].dataset.selectedHubs,a.selectedHubs.join(','));
 const points=[...r.data.facilities,...r.data.customers],west=Math.min(...points.map(x=>x.lon))-.35,east=Math.max(...points.map(x=>x.lon))+.35,south=Math.min(...points.map(x=>x.lat))-.3,north=Math.max(...points.map(x=>x.lat))+.3;
 for(const kind of ['hub','customer'])for(const n of ids['network-map'].querySelectorAll(`[data-${kind}-id]`)){assert.equal(n.tagName,'circle');near(+n.attrs.cx,55+(+n.dataset.lon-west)/(east-west)*790);near(+n.attrs.cy,490-(+n.dataset.lat-south)/(north-south)*430);n.events.click();assert.ok(ids['selection-detail'].children.length>3);}
 const routes=ids['network-map'].querySelectorAll('[data-route-hub]');assert.equal(routes.length,a.planning.allocations.length);routes.forEach(n=>{const x=a.planning.allocations.find(x=>x.hubId===n.dataset.routeHub&&x.customerId===n.dataset.routeCustomer);assert.equal(+n.dataset.units,x.unitsPerDay);const h=r.data.facilities.find(h=>h.id===x.hubId),c=r.data.customers.find(c=>c.id===x.customerId);near(+n.attrs.x1,55+(h.lon-west)/(east-west)*790);near(+n.attrs.y1,490-(h.lat-south)/(north-south)*430);near(+n.attrs.x2,55+(c.lon-west)/(east-west)*790);near(+n.attrs.y2,490-(c.lat-south)/(north-south)*430);});}
 check('optimized',model.run());ids['case-select'].value='S2';ids['case-select'].events.change();check('optimized',normal);ids['scenario-select'].value='baseline';ids['scenario-select'].events.change();check('baseline',normal);
 ids['scenario-select'].value='optimized';ids['demand-multiplier'].value='0';ids['model-form'].events.submit({preventDefault(){}});check('optimized',model.run({data:S2,demandMultiplier:0}));assert.match(ids['model-checks'].textContent,/평가 대상 없음/);
 ids['demand-multiplier'].value='1';ids['disruption-hub'].value='F2';ids['disruption-days'].value='7';ids['model-form'].events.submit({preventDefault(){}});check('optimized',blocked);
 ids['case-select'].value='regional';ids['disruption-days'].value='0';ids['case-select'].events.change();check('optimized',model.run({data:model.fixtures().regional}));
 ids['fixed-cost-multiplier'].value='11';ids['case-select'].value='S2';assert.doesNotThrow(()=>ids['case-select'].events.change());assert.equal(ids['model-results'].hidden,true);assert.match(ids['model-checks'].textContent,/고정비 배율은 0~10/);assert.equal(ids['network-map'].children.length,0);assert.equal(ids['top-kpis'].children.length,0);assert.deepEqual(ids['model-results'].dataset,{});ids['scenario-select'].events.change();assert.equal(ids['model-results'].hidden,true);ids['fixed-cost-multiplier'].value='1';ids['case-select'].events.change();assert.equal(ids['model-results'].hidden,false);check('optimized',normal);
 ids.days.value='0';ids['model-form'].events.submit({preventDefault(){}});assert.equal(ids['model-results'].hidden,true);ids.days.value='7';ids['model-form'].events.submit({preventDefault(){}});assert.equal(ids['model-results'].hidden,false);
});
test('R2 첫 증대 이후 실제 역간선 사용',()=>{assert.equal(reverse.optimized.planning.solverTrace[0].reverseEdges,0);assert.ok(reverse.optimized.planning.solverTrace.slice(1).some(s=>s.reverseEdges>0));near(reverse.optimized.planning.solverTrace[0].unitPathCost,k);});
test('지역 배송망 스트레스·용량·납기 민감도',()=>{
 const data=model.fixtures().regional;
 for(const [label,params] of [['정상',{}],['수요증가',{demandMultiplier:1.2}],['용량축소',{capacityMultiplier:.6}],['거점수1',{maxHubs:1}],['거점수4',{maxHubs:4}],['장애H2',{disruptionHub:'H2',disruptionDays:2}],['장애H3',{disruptionHub:'H3',disruptionDays:2}],['장애H1',{disruptionHub:'H1',disruptionDays:2}],['seed2026',{seed:2026}],['고정비0',{data:{...data,facilities:data.facilities.map(h=>({...h,fixedCostPerDay:0}))}}]])run('지역 '+label,{data,...params});
 const expensive=copy(data);expensive.facilities.forEach(h=>h.fixedCostPerDay*=10);run('지역 고정비10배',{data:expensive});
 const r=model.run({data});audit(r);
 assert.equal(r.data.facilities.length,4);assert.equal(r.data.customers.length,6);
 const deadlines=[4,6,8].map(hours=>({hours,...Object.fromEntries(['baseline','optimized'].map(name=>[name,r[name].simulation.orders.filter(o=>o.deliveredAt!==null&&o.deliveredAt<=o.createdAt+hours).length/r[name].simulation.kpis.demand]))}));
 assert.ok(deadlines[0].optimized<=deadlines[1].optimized&&deadlines[1].optimized<=deadlines[2].optimized);
 runs.push({label:'지역 납기 사후 평가 (API 납기 8h 유지)',deadlines});
});
for(const r of runs)for(const name of ['baseline','optimized'])if(r[name]){const full=model.run(r.params),a=full[name];r[name].capacity=full.data.facilities.map(h=>({hubId:h.id,capacityPerDay:Math.round(h.capacityPerDay*full.parameters.capacityMultiplier),plannedPerDay:sum(a.planning.allocations.filter(x=>x.hubId===h.id),x=>x.unitsPerDay),dispatchedByDay:a.simulation.daily.map(d=>a.simulation.orders.filter(o=>o.hubId===h.id&&o.day===d.day&&o.dispatchedAt!==null).length),disruptionLoss:a.simulation.orders.filter(o=>o.hubId===h.id&&o.unservedReason==='disruption').length}));}

const files=['app.js','index.html','model.js','model.test.cjs','README.md','style.css'];
const source=fs.readFileSync('model.test.cjs','utf8');
const calls=[...source.matchAll(/require\(([^)]*)\)/g)].map(x=>x[1]);
assert.deepEqual(calls,["'node:assert/strict'","'node:fs'","'node:vm'","'./model.js'"]);
const n=v=>Number(v.toFixed(6));
const lines=['## 실제 Node 자체 검사 요약', '', '실행: '+new Date().toISOString()+' · '+process.version+' · 독립 검증/실제 브라우저 아님.', '', '명령: node model.test.cjs --record. 아래 모든 실행은 원시 orders·planning·daily에서 비용/수요/용량/납기를 재계산하여 PASS. 수량 정확 일치; 비용·시간 max(1e-9, 상대1e-9), 별도 거리식 1e-5km.', '', ...logs.map(x=>'- PASS: '+x.name), '', '### 산술 기대값 / 관측값 / 판정', '| 검사 | 기대 | 관측 | 판정 |','|---|---:|---:|---|', '| S2 기준 일비용 | '+n(4+8*k)+' | '+n(normal.baseline.planning.totalCostPerDay)+' | PASS |','| S2 개선 일비용 | '+n(2+16*k)+' | '+n(normal.optimized.planning.totalCostPerDay)+' | PASS |','| R2 재배치 비용 | '+n(4*k)+' | '+n(reverse.optimized.planning.totalCostPerDay)+' | PASS |','| S2 F2 전기간 장애 비용 | 11214 | '+blocked.optimized.simulation.kpis.totalCost+' | PASS |', '', '### 실행별 핵심 비교', '기본 조건 seed42/7일/배율1/maxHubs2/장애없음. fixture와 변경 조건으로 재현. 계획비용은 일, 운영비용은 기간, 비율은 0~1, 리드는 h. 모든 행의 기대: 제약 잔차0·용량초과0·개선 계획비용 비악화·원시 재계산 일치; 관측: PASS.', '| 사례·변경 조건 | 대안·선택 | 계획비용 | 운영비용 | 배송률 | 정시율 | 리드 | 용량: 거점=계획/한도, 기간출고, 장애손실 |','|---|---|---:|---:|---:|---:|---:|---|'];
for(const r of runs){if(r.deadlines){lines.push('', '납기 사후 평가: '+JSON.stringify(r.deadlines));continue;}const {data,...changes}=r.params;changes.fixedCosts=data.facilities.map(h=>h.fixedCostPerDay);for(const name of ['baseline','optimized']){const a=r[name],v=a.kpis;lines.push('| '+r.label+'; '+data.provenance.version+'; '+JSON.stringify(changes)+' | '+name+' '+a.selectedHubs.join(',')+' | '+[a.planning.totalCostPerDay,v.totalCost,v.serviceRate,v.onTimeRate,v.meanLeadHours].map(n).join(' | ')+' | '+a.capacity.map(h=>h.hubId+'='+h.plannedPerDay+'/'+h.capacityPerDay+','+sum(h.dispatchedByDay,x=>x)+','+h.disruptionLoss).join('; ')+' |');}}
if(process.argv.includes('--record')){const path='README.md',old=fs.readFileSync(path,'utf8').split('\n<!-- EXECUTION_RECORD -->')[0];fs.writeFileSync(path,old+'\n<!-- EXECUTION_RECORD -->\n'+lines.join('\n')+'\n');}
const sizes=Object.fromEntries(files.map(p=>[p,fs.statSync(p).size]));const total=sum(Object.values(sizes),x=>x);for(const size of Object.values(sizes))assert.ok(size<=500000);assert.ok(total<=1000000);
console.log(JSON.stringify({tests:logs.length,passed:logs.length,requireAllowlist:'PASS',sizes,total,regional:runs.filter(r=>r.label.startsWith('지역')).map(r=>({label:r.label,baseline:r.baseline?.kpis,optimized:r.optimized?.kpis,deadlines:r.deadlines}))},null,2));
